version: "3"
services:
  mysql5.6:
    image: mysql:5.6
    container_name: ${MYSQL_CONTAINER_NAME_PREFIX}5.6
    ports:
      - 3356:3306
    environment:
      - MYSQL_DATABASE=bookstore
      - MYSQL_USER=user
      - MYSQL_PASSWORD=adminstore
      - MYSQL_ROOT_PASSWORD=simple